# Generated by Django 4.1.1 on 2022-09-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='agua',
            field=models.IntegerField(choices=[(1, '1 litro'), (1.5, '1.5 litros'), (2, '2 litros'), (2.5, '2.5 litros'), (3, '3 litros')], default=0),
        ),
    ]
