# Generated by Django 4.1.1 on 2022-11-18 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(choices=[('Perda de Peso', 'Perda de Peso'), ('Ganho de Massa', 'Ganho de Massa'), ('Definição', 'Definição'), ('Bem-Estar', 'Bem-Estar'), ('Manutenção de Físico', 'Manutenção de Físico')], default=None)),
                ('hours_per_day', models.PositiveIntegerField(default=None)),
                ('problemas', models.TextField(default=None)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
