# Generated by Django 4.1.1 on 2022-11-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_requestworkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestworkout',
            name='availability',
        ),
    ]
