# Generated by Django 4.1.1 on 2022-09-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_caracteristicas_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicas',
            name='peso_inicial',
            field=models.FloatField(default=0),
        ),
    ]
