# Generated by Django 4.1.1 on 2022-11-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_requestworkout_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestworkout',
            name='availability',
            field=models.BooleanField(choices=[('Segunda-Feira', 'Segunda-Feira'), ('Terça-Feira', 'Terça-Feira'), ('Quarta-Feira', 'Quarta-Feira'), ('Quinta-Feira', 'Quinta-Feira'), ('Sexta-Feira', 'Sexta-Feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default=None),
        ),
    ]
