# Generated by Django 4.1.1 on 2022-10-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_caracteristicas_idade_alter_ingestao_agua_and_more'),
        ('main', '0008_ingestao_created'),
    ]

    operations = [
    ]
