# Generated by Django 4.1.1 on 2022-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_requestworkout_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestworkout',
            name='availability',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
