# Generated by Django 4.1.1 on 2022-10-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20221001_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas',
            name='altura',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='idade',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='peso_atual',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='peso_inicial',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='ingestao',
            name='agua',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='metas',
            name='agua',
            field=models.FloatField(choices=[(1, '1 litro'), (1.5, '1.5 litros'), (2, '2 litros'), (2.5, '2.5 litros'), (3, '3 litros')], default=None),
        ),
        migrations.AlterField(
            model_name='metas',
            name='calorias',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='metas',
            name='peso',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='pesohistory',
            name='peso',
            field=models.FloatField(default=None),
        ),
    ]
