# Generated by Django 4.1.1 on 2022-10-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_caracteristicas_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='agua',
            field=models.FloatField(choices=[(1, '1 litro'), (1.5, '1.5 litros'), (2, '2 litros'), (2.5, '2.5 litros'), (3, '3 litros'), (3.5, '3.5 litros'), (4, '4 litros'), (4.5, '4.5 litros'), (5, '5 litros')], default=None),
        ),
    ]
