# Generated by Django 4.1.1 on 2022-10-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_metas_agua'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestao',
            name='calorias',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
