# Generated by Django 4.1.1 on 2022-10-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_ingestao_calorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestao',
            name='calorias',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
