# Generated by Django 4.1.1 on 2022-10-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_ingestao_calorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestaoCalorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias', models.PositiveIntegerField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingestao',
            name='calorias',
        ),
    ]
