# Generated by Django 4.1.1 on 2022-10-15 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ingestaocalorias_remove_ingestao_calorias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngestaoCalorias',
        ),
    ]
